export const FETCHING_PROVIDER_DATA = 'FETCHING_PROVIDER_DATA'
export const GET_PROVIDER_DATA_SUCCESS = 'GET_PROVIDER_DATA_SUCCESS'
export const GET_PROVIDER_DATA_FAILURE = 'GET_PROVIDER_DATA_FAILURE'
